# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-30 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('original_title', models.CharField(blank=True, max_length=60)),
                ('douban_id', models.CharField(max_length=60, unique=True)),
                ('douban_rating', models.FloatField(blank=True, default=0.0)),
                ('imdb_id', models.CharField(blank=True, max_length=60)),
                ('imdb_rating', models.FloatField(blank=True, default=0.0)),
                ('rotten_id', models.CharField(blank=True, max_length=60)),
                ('rotten_rating', models.IntegerField(blank=True, default=0)),
                ('rotten_audience_rating', models.IntegerField(blank=True, default=0)),
                ('release_date', models.DateField(blank=True)),
                ('poster', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('online_source', models.TextField(blank=True)),
                ('episodes', models.IntegerField(blank=True, default=0)),
                ('current_episode', models.IntegerField(blank=True, default=0)),
                ('date_watched', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('visual_type', models.TextField(default='movie')),
            ],
            options={
                'ordering': ['-date_watched'],
            },
        ),
    ]
