# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('url', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('artist', models.CharField(blank=True, max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('visual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visuals.Visual')),
            ],
        ),
    ]
