# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0002_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('date_updated',)},
        ),
    ]
