# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0006_visual_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='air_day',
            field=models.TextField(blank=True),
        ),
    ]
