# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0007_visual_air_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('title_zh', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('visuals', models.ManyToManyField(to='visuals.Visual')),
            ],
            options={
                'ordering': ('date_updated',),
            },
        ),
    ]
