# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0009_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='duration',
            field=models.TextField(blank=True),
        ),
    ]
